# Generated by Django 2.2 on 2019-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_request', models.CharField(max_length=120)),
                ('img', models.CharField(max_length=250)),
                ('ip', models.CharField(default='127.0.0.1', max_length=120)),
                ('mobile', models.TextField(blank=True, default='Android', null=True)),
                ('user_id', models.IntegerField(default=0)),
                ('preds', models.CharField(default='0', max_length=80)),
            ],
        ),
    ]
